export default {
  GET_API: 'GET_API',
  GET_DATA_PIE_CHART: 'GET_DATA_PIE_CHART',
  GET_DATA_HORIZONTAL_CHART: 'GET_DATA_HORIZONTAL_CHART',
  GET_DATA_LINE_CHART: 'GET_DATA_LINE_CHART',
  GET_DATA_PIE_CHART_2: 'GET_DATA_PIE_CHART_2'
};